[package]
name = "imgui_luminance"
version = "0.1.0"
authors = ["Benoit Eudier <benoit.eudier@gmail.com>"]
edition = "2018"


[dependencies]
luminance = "0.39.0"
luminance-derive = "0.5"
luminance-glfw = "0.12"
luminance-windowing = "0.8"
imgui = "0.5.0"
